In [10]:
import urllib.request
import json
from pprint import pprint
import pandas as pd
from pandas.io.json import json_normalize

In [11]:
url = r'http://datapoint.metoffice.gov.uk/public/data/val/wxobs/all/json/3772?res=hourly&key=acea5d3c-ec7d-49ad-9828-29f485a93181'

In [14]:
with urllib.request.urlopen(url) as response:
    html = response.read()
    htmld = json.loads(html)
    pprint(htmld)

{'SiteRep': {'DV': {'Location': {'Period': [{'Rep': [{'$': '660',
                                                      'D': 'WSW',
                                                      'Dp': '4.3',
                                                      'H': '74.6',
                                                      'P': '1026',
                                                      'Pt': 'R',
                                                      'S': '6',
                                                      'T': '8.5',
                                                      'V': '13000',
                                                      'W': '1'},
                                                     {'$': '720',
                                                      'D': 'S',
                                                      'Dp': '5.0',
                                                      'H': '67.9',
                                                      'P': '1025',
                                                      'Pt': 'F',
                                                      'S': '5',
                                                      'T': '10.6',
                                                      'V': '17000',
                                                      'W': '1'},
                                                     {'$': '780',
                                                      'D': 'SSW',
                                                      'Dp': '5.0',
                                                      'H': '63.8',
                                                      'P': '1025',
                                                      'Pt': 'F',
                                                      'S': '6',
                                                      'T': '11.5',
                                                      'V': '30000',
                                                      'W': '1'},
                                                     {'$': '840',
                                                      'D': 'SW',
                                                      'Dp': '3.6',
                                                      'H': '59.4',
                                                      'P': '1025',
                                                      'Pt': 'F',
                                                      'S': '6',
                                                      'T': '11.1',
                                                      'V': '40000',
                                                      'W': '1'},
                                                     {'$': '900',
                                                      'D': 'SW',
                                                      'Dp': '3.6',
                                                      'H': '58.2',
                                                      'P': '1024',
                                                      'Pt': 'F',
                                                      'S': '7',
                                                      'T': '11.4',
                                                      'V': '35000',
                                                      'W': '1'},
                                                     {'$': '960',
                                                      'D': 'SSW',
                                                      'Dp': '3.6',
                                                      'H': '62.2',
                                                      'P': '1024',
                                                      'Pt': 'F',
                                                      'S': '7',
                                                      'T': '10.4',
                                                      'V': '35000',
                                                      'W': '1'},
                                                     {'$': '1020',
                                                      'D': 'S',
                                                      'Dp': '3.6',
                                                      'H': '67.2',
                                                      'P': '1024',
                                                      'Pt': 'F',
                                                      'S': '7',
                                                      'T': '9.3',
                                                      'V': '30000',
                                                      'W': '0'},
                                                     {'$': '1080',
                                                      'D': 'S',
                                                      'Dp': '4.2',
                                                      'H': '74.4',
                                                      'P': '1024',
                                                      'Pt': 'F',
                                                      'S': '8',
                                                      'T': '8.4',
                                                      'V': '20000',
                                                      'W': '0'},
                                                     {'$': '1140',
                                                      'D': 'SSE',
                                                      'Dp': '4.3',
                                                      'H': '80.9',
                                                      'P': '1024',
                                                      'Pt': 'F',
                                                      'S': '8',
                                                      'T': '7.3',
                                                      'V': '15000',
                                                      'W': '0'},
                                                     {'$': '1200',
                                                      'D': 'S',
                                                      'Dp': '4.2',
                                                      'H': '82.7',
                                                      'P': '1024',
                                                      'Pt': 'F',
                                                      'S': '7',
                                                      'T': '6.9',
                                                      'V': '18000',
                                                      'W': '0'},
                                                     {'$': '1260',
                                                      'D': 'SSE',
                                                      'Dp': '4.4',
                                                      'H': '84.9',
                                                      'P': '1024',
                                                      'Pt': 'F',
                                                      'S': '7',
                                                      'T': '6.7',
                                                      'V': '19000',
                                                      'W': '2'},
                                                     {'$': '1320',
                                                      'D': 'SSE',
                                                      'Dp': '4.6',
                                                      'H': '83.9',
                                                      'P': '1023',
                                                      'Pt': 'F',
                                                      'S': '9',
                                                      'T': '7.1',
                                                      'V': '19000',
                                                      'W': '7'},
                                                     {'$': '1380',
                                                      'D': 'SSE',
                                                      'Dp': '4.9',
                                                      'H': '80.6',
                                                      'P': '1023',
                                                      'Pt': 'F',
                                                      'S': '9',
                                                      'T': '8.0',
                                                      'V': '27000',
                                                      'W': '8'}],
                                             'type': 'Day',
                                             'value': '2017-11-06Z'},
                                            {'Rep': [{'$': '0',
                                                      'D': 'SSE',
                                                      'Dp': '5.5',
                                                      'H': '82.9',
                                                      'P': '1022',
                                                      'Pt': 'F',
                                                      'S': '10',
                                                      'T': '8.2',
                                                      'V': '27000',
                                                      'W': '8'},
                                                     {'$': '60',
                                                      'D': 'SSE',
                                                      'Dp': '5.9',
                                                      'H': '80.7',
                                                      'P': '1021',
                                                      'Pt': 'F',
                                                      'S': '13',
                                                      'T': '9.0',
                                                      'V': '40000',
                                                      'W': '8'},
                                                     {'$': '120',
                                                      'D': 'S',
                                                      'Dp': '7.3',
                                                      'H': '87.1',
                                                      'P': '1021',
                                                      'Pt': 'F',
                                                      'S': '14',
                                                      'T': '9.3',
                                                      'V': '35000',
                                                      'W': '8'},
                                                     {'$': '180',
                                                      'D': 'SSE',
                                                      'Dp': '7.8',
                                                      'H': '91.4',
                                                      'P': '1020',
                                                      'Pt': 'F',
                                                      'S': '13',
                                                      'T': '9.1',
                                                      'V': '35000',
                                                      'W': '8'},
                                                     {'$': '240',
                                                      'D': 'S',
                                                      'Dp': '7.6',
                                                      'H': '89.0',
                                                      'P': '1019',
                                                      'Pt': 'F',
                                                      'S': '10',
                                                      'T': '9.3',
                                                      'V': '30000',
                                                      'W': '8'},
                                                     {'$': '300',
                                                      'D': 'S',
                                                      'Dp': '7.3',
                                                      'H': '83.7',
                                                      'P': '1019',
                                                      'Pt': 'F',
                                                      'S': '9',
                                                      'T': '9.9',
                                                      'V': '23000',
                                                      'W': '8'},
                                                     {'$': '360',
                                                      'D': 'S',
                                                      'Dp': '7.0',
                                                      'H': '82.0',
                                                      'P': '1019',
                                                      'Pt': 'F',
                                                      'S': '9',
                                                      'T': '9.9',
                                                      'V': '30000',
                                                      'W': '8'},
                                                     {'$': '420',
                                                      'D': 'S',
                                                      'Dp': '6.9',
                                                      'H': '77.6',
                                                      'P': '1018',
                                                      'Pt': 'F',
                                                      'S': '11',
                                                      'T': '10.6',
                                                      'V': '30000',
                                                      'W': '8'},
                                                     {'$': '480',
                                                      'D': 'S',
                                                      'Dp': '7.0',
                                                      'H': '77.6',
                                                      'P': '1018',
                                                      'Pt': 'F',
                                                      'S': '6',
                                                      'T': '10.7',
                                                      'V': '35000',
                                                      'W': '7'},
                                                     {'$': '540',
                                                      'D': 'SE',
                                                      'Dp': '7.1',
                                                      'H': '77.7',
                                                      'P': '1018',
                                                      'Pt': 'F',
                                                      'S': '9',
                                                      'T': '10.8',
                                                      'V': '25000',
                                                      'W': '8'},
                                                     {'$': '600',
                                                      'D': 'S',
                                                      'Dp': '7.6',
                                                      'H': '74.2',
                                                      'P': '1017',
                                                      'Pt': 'F',
                                                      'S': '13',
                                                      'T': '12.0',
                                                      'V': '30000',
                                                      'W': '8'},
                                                     {'$': '660',
                                                      'D': 'S',
                                                      'Dp': '7.8',
                                                      'H': '74.2',
                                                      'P': '1017',
                                                      'Pt': 'F',
                                                      'S': '13',
                                                      'T': '12.2',
                                                      'V': '27000',
                                                      'W': '8'}],
                                             'type': 'Day',
                                             'value': '2017-11-07Z'}],
                                 'continent': 'EUROPE',
                                 'country': 'ENGLAND',
                                 'elevation': '25.0',
                                 'i': '3772',
                                 'lat': '51.479',
                                 'lon': '-0.4491',
                                 'name': 'HEATHROW'},
                    'dataDate': '2017-11-07T11:00:00Z',
                    'type': 'Obs'},
             'Wx': {'Param': [{'$': 'Wind Gust', 'name': 'G', 'units': 'mph'},
                              {'$': 'Temperature', 'name': 'T', 'units': 'C'},
                              {'$': 'Visibility', 'name': 'V', 'units': 'm'},
                              {'$': 'Wind Direction',
                               'name': 'D',
                               'units': 'compass'},
                              {'$': 'Wind Speed', 'name': 'S', 'units': 'mph'},
                              {'$': 'Weather Type', 'name': 'W', 'units': ''},
                              {'$': 'Pressure', 'name': 'P', 'units': 'hpa'},
                              {'$': 'Pressure Tendency',
                               'name': 'Pt',
                               'units': 'Pa/s'},
                              {'$': 'Dew Point', 'name': 'Dp', 'units': 'C'},
                              {'$': 'Screen Relative Humidity',
                               'name': 'H',
                               'units': '%'}]}}}

In [38]:
#The first parts that are bracketed (before the ,) is
# the sliced parts then just before the data you want, add a comma
# in order to display the data within 'Rep'
weather = json_normalize(htmld['SiteRep']['DV']['Location']['Period'], ['Rep'], ['value', 'type'])

In [39]:
weather

       $    D   Dp     H     P Pt   S     T      V  W        value type
0    660  WSW  4.3  74.6  1026  R   6   8.5  13000  1  2017-11-06Z  Day
1    720    S  5.0  67.9  1025  F   5  10.6  17000  1  2017-11-06Z  Day
2    780  SSW  5.0  63.8  1025  F   6  11.5  30000  1  2017-11-06Z  Day
3    840   SW  3.6  59.4  1025  F   6  11.1  40000  1  2017-11-06Z  Day
4    900   SW  3.6  58.2  1024  F   7  11.4  35000  1  2017-11-06Z  Day
5    960  SSW  3.6  62.2  1024  F   7  10.4  35000  1  2017-11-06Z  Day
6   1020    S  3.6  67.2  1024  F   7   9.3  30000  0  2017-11-06Z  Day
7   1080    S  4.2  74.4  1024  F   8   8.4  20000  0  2017-11-06Z  Day
8   1140  SSE  4.3  80.9  1024  F   8   7.3  15000  0  2017-11-06Z  Day
9   1200    S  4.2  82.7  1024  F   7   6.9  18000  0  2017-11-06Z  Day
10  1260  SSE  4.4  84.9  1024  F   7   6.7  19000  2  2017-11-06Z  Day
11  1320  SSE  4.6  83.9  1023  F   9   7.1  19000  7  2017-11-06Z  Day
12  1380  SSE  4.9  80.6  1023  F   9   8.0  27000  8  2017-11-06Z  Day
13     0  SSE  5.5  82.9  1022  F  10   8.2  27000  8  2017-11-07Z  Day
14    60  SSE  5.9  80.7  1021  F  13   9.0  40000  8  2017-11-07Z  Day
15   120    S  7.3  87.1  1021  F  14   9.3  35000  8  2017-11-07Z  Day
16   180  SSE  7.8  91.4  1020  F  13   9.1  35000  8  2017-11-07Z  Day
17   240    S  7.6  89.0  1019  F  10   9.3  30000  8  2017-11-07Z  Day
18   300    S  7.3  83.7  1019  F   9   9.9  23000  8  2017-11-07Z  Day
19   360    S  7.0  82.0  1019  F   9   9.9  30000  8  2017-11-07Z  Day
20   420    S  6.9  77.6  1018  F  11  10.6  30000  8  2017-11-07Z  Day
21   480    S  7.0  77.6  1018  F   6  10.7  35000  7  2017-11-07Z  Day
22   540   SE  7.1  77.7  1018  F   9  10.8  25000  8  2017-11-07Z  Day
23   600    S  7.6  74.2  1017  F  13  12.0  30000  8  2017-11-07Z  Day
24   660    S  7.8  74.2  1017  F  13  12.2  27000  8  2017-11-07Z  Day

# How to create a column which shows if the time is daylight or not.

In [ ]:
# The hour column labelled $, so we want to extract it

In [53]:
t = weather[['$']]
#The hour column is encased in 2 square brackets
# to show it is a DataFrame

In [57]:
# Imagine that this t is just the $, it was re-run after the daylight
#if statement
t

       $  daylight
0    660         1
1    720         1
2    780         1
3    840         1
4    900         1
5    960         1
6   1020         0
7   1080         0
8   1140         0
9   1200         0
10  1260         0
11  1320         0
12  1380         0
13     0         0
14    60         0
15   120         0
16   180         0
17   240         0
18   300         0
19   360         0
20   420         1
21   480         1
22   540         1
23   600         1
24   660         1

In [55]:
# t in daylight is what we want, and we are mapping every item in $ to
# a new function i.e. daylight
t['daylight'] = t['$'].map(daylight)

C:\Users\Student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [66]:
t['workhours'] = t['$'].map(lambda x: 1 if int(x) >= 540 and int(x) <= 960 else 0)

C:\Users\Student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [49]:
def daylight(m):
    if int(m) >= 420 and int(m) <= 960:
        r = 1
    else:
        r = 0
    return r

In [68]:
t.drop('hours', 1)

       $  daylight  workhours
0    660         1          1
1    720         1          1
2    780         1          1
3    840         1          1
4    900         1          1
5    960         1          1
6   1020         0          0
7   1080         0          0
8   1140         0          0
9   1200         0          0
10  1260         0          0
11  1320         0          0
12  1380         0          0
13     0         0          0
14    60         0          0
15   120         0          0
16   180         0          0
17   240         0          0
18   300         0          0
19   360         0          0
20   420         1          0
21   480         1          0
22   540         1          1
23   600         1          1
24   660         1          1

In [74]:
t['hours'] = t['$'].map(lambda x: int(x)/60)

SyntaxError: keyword can't be an expression (<ipython-input-74-175879a0940b>, line 1)

In [73]:
t

       $  daylight  hours  workhours
0    660         1   11.0          1
1    720         1   12.0          1
2    780         1   13.0          1
3    840         1   14.0          1
4    900         1   15.0          1
5    960         1   16.0          1
6   1020         0   17.0          0
7   1080         0   18.0          0
8   1140         0   19.0          0
9   1200         0   20.0          0
10  1260         0   21.0          0
11  1320         0   22.0          0
12  1380         0   23.0          0
13     0         0    0.0          0
14    60         0    1.0          0
15   120         0    2.0          0
16   180         0    3.0          0
17   240         0    4.0          0
18   300         0    5.0          0
19   360         0    6.0          0
20   420         1    7.0          0
21   480         1    8.0          0
22   540         1    9.0          1
23   600         1   10.0          1
24   660         1   11.0          1

### Joining tables

In [75]:
weather.merge(t, how ='inner')

,$,D,Dp,H,P,Pt,S,T,V,W,value,type,daylight,hours,workhours
0,660,WSW,4.3,74.6,1026,R,6,8.5,13000,1,2017-11-06Z,Day,1,11.0,1
1,660,WSW,4.3,74.6,1026,R,6,8.5,13000,1,2017-11-06Z,Day,1,11.0,1
2,660,S,7.8,74.2,1017,F,13,12.2,27000,8,2017-11-07Z,Day,1,11.0,1
3,660,S,7.8,74.2,1017,F,13,12.2,27000,8,2017-11-07Z,Day,1,11.0,1
4,720,S,5.0,67.9,1025,F,5,10.6,17000,1,2017-11-06Z,Day,1,12.0,1
5,780,SSW,5.0,63.8,1025,F,6,11.5,30000,1,2017-11-06Z,Day,1,13.0,1
6,840,SW,3.6,59.4,1025,F,6,11.1,40000,1,2017-11-06Z,Day,1,14.0,1
7,900,SW,3.6,58.2,1024,F,7,11.4,35000,1,2017-11-06Z,Day,1,15.0,1
8,960,SSW,3.6,62.2,1024,F,7,10.4,35000,1,2017-11-06Z,Day,1,16.0,1
9,1020,S,3.6,67.2,1024,F,7,9.3,30000,0,2017-11-06Z,Day,0,17.0,0
10,1080,S,4.2,74.4,1024,F,8,8.4,20000,0,2017-11-06Z,Day,0,18.0,0
11,1140,SSE,4.3,80.9,1024,F,8,7.3,15000,0,2017-11-06Z,Day,0,19.0,0
12,1200,S,4.2,82.7,1024,F,7,6.9,18000,0,2017-11-06Z,Day,0,20.0,0
13,1260,SSE,4.4,84.9,1024,F,7,6.7,19000,2,2017-11-06Z,Day,0,21.0,0
14,1320,SSE,4.6,83.9,1023,F,9,7.1,19000,7,2017-11-06Z,Day,0,22.0,0
15,1380,SSE,4.9,80.6,1023,F,9,8.0,27000,8,2017-11-06Z,Day,0,23.0,0
16,0,SSE,5.5,82.9,1022,F,10,8.2,27000,8,2017-11-07Z,Day,0,0.0,0
17,60,SSE,5.9,80.7,1021,F,13,9.0,40000,8,2017-11-07Z,Day,0,1.0,0
18,120,S,7.3,87.1,1021,F,14,9.3,35000,8,2017-11-07Z,Day,0,2.0,0
19,180,SSE,7.8,91.4,1020,F,13,9.1,35000,8,2017-11-07Z,Day,0,3.0,0
20,240,S,7.6,89.0,1019,F,10,9.3,30000,8,2017-11-07Z,Day,0,4.0,0
21,300,S,7.3,83.7,1019,F,9,9.9,23000,8,2017-11-07Z,Day,0,5.0,0
22,360,S,7.0,82.0,1019,F,9,9.9,30000,8,2017-11-07Z,Day,0,6.0,0
23,420,S,6.9,77.6,1018,F,11,10.6,30000,8,2017-11-07Z,Day,1,7.0,0
24,480,S,7.0,77.6,1018,F,6,10.7,35000,7,2017-11-07Z,Day,1,8.0,0
25,540,SE,7.1,77.7,1018,F,9,10.8,25000,8,2017-11-07Z,Day,1,9.0,1
26,600,S,7.6,74.2,1017,F,13,12.0,30000,8,2017-11-07Z,Day,1,10.0,1

In [77]:
#on tells you what you want to join on
#since $ is commom to both tables it knows what to join on
#if you wanted to merge on another table you just add on .merge

### Concat tables

In [78]:
#this returns answer as (rows, columns)
weather.shape

(25, 12)

In [80]:
#now the number of rows are 50, to show that the height as changed
# therefore the tables is 'on top of one another'
double_weather = pd.concat([weather, weather], axis=0)
double_weather.shape

(50, 12)

In [83]:
double_weather.drop_duplicates

<bound method DataFrame.drop_duplicates of        $    D   Dp     H     P Pt   S     T      V  W        value type
0    660  WSW  4.3  74.6  1026  R   6   8.5  13000  1  2017-11-06Z  Day
1    720    S  5.0  67.9  1025  F   5  10.6  17000  1  2017-11-06Z  Day
2    780  SSW  5.0  63.8  1025  F   6  11.5  30000  1  2017-11-06Z  Day
3    840   SW  3.6  59.4  1025  F   6  11.1  40000  1  2017-11-06Z  Day
4    900   SW  3.6  58.2  1024  F   7  11.4  35000  1  2017-11-06Z  Day
5    960  SSW  3.6  62.2  1024  F   7  10.4  35000  1  2017-11-06Z  Day
6   1020    S  3.6  67.2  1024  F   7   9.3  30000  0  2017-11-06Z  Day
7   1080    S  4.2  74.4  1024  F   8   8.4  20000  0  2017-11-06Z  Day
8   1140  SSE  4.3  80.9  1024  F   8   7.3  15000  0  2017-11-06Z  Day
9   1200    S  4.2  82.7  1024  F   7   6.9  18000  0  2017-11-06Z  Day
10  1260  SSE  4.4  84.9  1024  F   7   6.7  19000  2  2017-11-06Z  Day
11  1320  SSE  4.6  83.9  1023  F   9   7.1  19000  7  2017-11-06Z  Day
12  1380  SSE  4.9  80.6  1023  F   9   8.0  27000  8  2017-11-06Z  Day
13     0  SSE  5.5  82.9  1022  F  10   8.2  27000  8  2017-11-07Z  Day
14    60  SSE  5.9  80.7  1021  F  13   9.0  40000  8  2017-11-07Z  Day
15   120    S  7.3  87.1  1021  F  14   9.3  35000  8  2017-11-07Z  Day
16   180  SSE  7.8  91.4  1020  F  13   9.1  35000  8  2017-11-07Z  Day
17   240    S  7.6  89.0  1019  F  10   9.3  30000  8  2017-11-07Z  Day
18   300    S  7.3  83.7  1019  F   9   9.9  23000  8  2017-11-07Z  Day
19   360    S  7.0  82.0  1019  F   9   9.9  30000  8  2017-11-07Z  Day
20   420    S  6.9  77.6  1018  F  11  10.6  30000  8  2017-11-07Z  Day
21   480    S  7.0  77.6  1018  F   6  10.7  35000  7  2017-11-07Z  Day
22   540   SE  7.1  77.7  1018  F   9  10.8  25000  8  2017-11-07Z  Day
23   600    S  7.6  74.2  1017  F  13  12.0  30000  8  2017-11-07Z  Day
24   660    S  7.8  74.2  1017  F  13  12.2  27000  8  2017-11-07Z  Day
0    660  WSW  4.3  74.6  1026  R   6   8.5  13000  1  2017-11-06Z  Day
1    720    S  5.0  67.9  1025  F   5  10.6  17000  1  2017-11-06Z  Day
2    780  SSW  5.0  63.8  1025  F   6  11.5  30000  1  2017-11-06Z  Day
3    840   SW  3.6  59.4  1025  F   6  11.1  40000  1  2017-11-06Z  Day
4    900   SW  3.6  58.2  1024  F   7  11.4  35000  1  2017-11-06Z  Day
5    960  SSW  3.6  62.2  1024  F   7  10.4  35000  1  2017-11-06Z  Day
6   1020    S  3.6  67.2  1024  F   7   9.3  30000  0  2017-11-06Z  Day
7   1080    S  4.2  74.4  1024  F   8   8.4  20000  0  2017-11-06Z  Day
8   1140  SSE  4.3  80.9  1024  F   8   7.3  15000  0  2017-11-06Z  Day
9   1200    S  4.2  82.7  1024  F   7   6.9  18000  0  2017-11-06Z  Day
10  1260  SSE  4.4  84.9  1024  F   7   6.7  19000  2  2017-11-06Z  Day
11  1320  SSE  4.6  83.9  1023  F   9   7.1  19000  7  2017-11-06Z  Day
12  1380  SSE  4.9  80.6  1023  F   9   8.0  27000  8  2017-11-06Z  Day
13     0  SSE  5.5  82.9  1022  F  10   8.2  27000  8  2017-11-07Z  Day
14    60  SSE  5.9  80.7  1021  F  13   9.0  40000  8  2017-11-07Z  Day
15   120    S  7.3  87.1  1021  F  14   9.3  35000  8  2017-11-07Z  Day
16   180  SSE  7.8  91.4  1020  F  13   9.1  35000  8  2017-11-07Z  Day
17   240    S  7.6  89.0  1019  F  10   9.3  30000  8  2017-11-07Z  Day
18   300    S  7.3  83.7  1019  F   9   9.9  23000  8  2017-11-07Z  Day
19   360    S  7.0  82.0  1019  F   9   9.9  30000  8  2017-11-07Z  Day
20   420    S  6.9  77.6  1018  F  11  10.6  30000  8  2017-11-07Z  Day
21   480    S  7.0  77.6  1018  F   6  10.7  35000  7  2017-11-07Z  Day
22   540   SE  7.1  77.7  1018  F   9  10.8  25000  8  2017-11-07Z  Day
23   600    S  7.6  74.2  1017  F  13  12.0  30000  8  2017-11-07Z  Day
24   660    S  7.8  74.2  1017  F  13  12.2  27000  8  2017-11-07Z  Day>